Fix grammar sync check in Windows CI
tlaplus/tlaplus pull request #968
Opened 2024-06-21 16:40 UTC by ahelwer

This step currently fails on Windows because it uses powershell, and also because the line endings are not renormalized.

2024-06-21 16:45 UTC, lemmy commented
This check should be done by the ant build; otherwise, it should be omitted entirely. Considering how rarely the grammar file is modified, it may be best to skip this check altogether.

2024-06-21 17:29 UTC, ahelwer commented
@markus this seems like an excellent place to put our email discussion about reversion steps to use, don't you think?

2024-06-21 17:37 UTC, lemmy commented
Please keep comments to technical discussions. Thank you!

2024-06-21 17:38 UTC, ahelwer commented
This is a technical discussion. The process by which we decide these things is a technical discussion.

2024-06-21 19:18 UTC, lemmy requested changes
This check should be performed as part of the Ant build to a) ensure platform independence and b) to be enforced locally (pre-push).  However, given the stability of the language grammar, it can likely be skipped/removed altogether.

2024-10-11 18:21 UTC, closed without merging

2024-10-11 18:23 UTC, ahelwer commented
I believe #1013 resolves this issue as the difference was due to git checking out the file with CRLF line endings on windows, which the Ant generate task overwrote. Now with those changes the generate task leaves CRLF line endings unchanged on windows.